import React, { useState, useEffect } from 'react';
import { useAppStore } from '../../lib/store';
import { formatLevel } from '../../lib/format';
import {
  X,
  FileText,
  Code2,
  Printer,
  Share2,
  Copy,
  Check,
  Download,
  Sparkles,
} from 'lucide-react';
import { toast } from 'sonner';

export interface ExportShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  onTriggerConfetti?: () => void;
}

export const ExportShareModal: React.FC<ExportShareModalProps> = ({
  isOpen,
  onClose,
  onTriggerConfetti,
}) => {
  const { profile, roadmap, gaps, skills } = useAppStore();
  const [copiedLink, setCopiedLink] = useState(false);
  const [activeTab, setActiveTab] = useState<'export' | 'share'>('export');

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isOpen) onClose();
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  // Generate Markdown Curriculum
  const handleExportMarkdown = () => {
    if (!profile || !roadmap) {
      toast.error('No active roadmap loaded to export.');
      return;
    }

    const mdContent = `# CareerForge AI — Personalized Preparation Roadmap
**Target Role:** ${profile.target_role}
**Student:** ${profile.name} (${profile.degree} · Year ${profile.year})
**Roadmap Revision:** v${roadmap.version.toFixed(1)}
**Total Estimated Commitment:** ${roadmap.total_estimated_hours} hours (${roadmap.available_hours_per_week} hrs/week ≈ ${roadmap.estimated_weeks} weeks)

---

## 1. Skill Gap Diagnostic & Market Benchmark
| Skill | Current Level | Required Level | Gap | Priority |
| :--- | :---: | :---: | :---: | :---: |
${gaps
  .map(
    (g) =>
      `| **${g.skill}** | ${formatLevel(g.current_level)} / 5.0 | ${formatLevel(
        g.required_level
      )} / 5.0 | -${formatLevel(g.gap)} | ${g.priority} |`
  )
  .join('\n')}

---

## 2. Phased Study Execution Curriculum
${roadmap.phases
  .map(
    (phase) => `### Phase ${phase.phase_number}: ${phase.title}
- **Estimated Commitment:** ${phase.estimated_hours} hours
- **Core Skills Covered:** ${phase.skills_covered.join(', ')}

#### Learning Milestones:
${(phase.learning_objectives || []).map((m) => `  - [ ] ${m}`).join('\n')}

#### Recommended Guides & Resources:
${(phase.resources || []).map((r) => `  - [${r.title}](${r.url_or_ref}) (${r.resource_type})`).join('\n')}
`
  )
  .join('\n')}

---
*Generated by CareerForge AI • Deterministic closed-loop placement engine*
`;

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `careerforge-${profile.target_role.toLowerCase().replace(/\s+/g, '-')}-roadmap.md`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Roadmap exported as Markdown file (.md)');
    onTriggerConfetti?.();
  };

  // Generate JSON Payload
  const handleExportJSON = () => {
    if (!profile || !roadmap) {
      toast.error('No active roadmap loaded to export.');
      return;
    }

    const payload = {
      profile,
      skills,
      gaps,
      roadmap,
      exportedAt: new Date().toISOString(),
      generator: 'CareerForge AI v2.0',
    };

    const blob = new Blob([JSON.stringify(payload, null, 2)], {
      type: 'application/json;charset=utf-8',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `careerforge-${profile.target_role.toLowerCase().replace(/\s+/g, '-')}-data.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('CareerForge payload exported as JSON (.json)');
    onTriggerConfetti?.();
  };

  // Native Print / PDF
  const handlePrintPDF = () => {
    window.print();
  };

  // Generate Shareable Link
  const sharePayload = {
    role: profile?.target_role || 'Backend Engineer',
    hours: roadmap?.available_hours_per_week || 20,
    skills: skills.map((s) => `${s.name}:${s.proficiency}`).join(','),
  };
  const encodedShare = encodeURIComponent(btoa(JSON.stringify(sharePayload)));
  const shareUrl = `${window.location.origin}${window.location.pathname}#plan=${encodedShare}`;

  const handleCopyShareLink = async () => {
    try {
      await navigator.clipboard.writeText(shareUrl);
      setCopiedLink(true);
      toast.success('Shareable plan link copied to clipboard!');
      onTriggerConfetti?.();
      setTimeout(() => setCopiedLink(false), 2500);
    } catch {
      toast.error('Could not copy link to clipboard');
    }
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fadeIn select-none"
      onClick={onClose}
      role="dialog"
      aria-modal="true"
      aria-labelledby="export-title"
    >
      <div
        className="relative w-full max-w-lg rounded-3xl border border-[var(--border)] bg-[var(--bg-elev-1)] shadow-2xl p-6 sm:p-7 space-y-5"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between pb-3 border-b border-[var(--border)]">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-[var(--accent-mint)]/10 text-[var(--accent-mint)] flex items-center justify-center border border-[var(--accent-mint)]/30">
              <Download className="w-4 h-4" />
            </div>
            <div>
              <h3 id="export-title" className="text-base font-bold font-display text-[var(--text)]">
                Export & Share Study Plan
              </h3>
              <p className="text-xs text-[var(--text-muted)]">
                Download your roadmap curriculum or copy a shareable link
              </p>
            </div>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="w-8 h-8 rounded-xl text-[var(--text-muted)] hover:text-[var(--text)] hover:bg-[var(--bg-elev-2)] flex items-center justify-center cursor-pointer transition-colors border border-transparent hover:border-[var(--border)]"
            aria-label="Close export modal"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Tab switcher */}
        <div className="flex gap-2 border-b border-[var(--border)] pb-2 font-mono text-xs">
          <button
            type="button"
            onClick={() => setActiveTab('export')}
            className={`pb-1 px-1.5 border-b-2 font-semibold transition-colors cursor-pointer ${
              activeTab === 'export'
                ? 'border-[var(--accent-mint)] text-[var(--accent-mint)]'
                : 'border-transparent text-[var(--text-muted)] hover:text-[var(--text)]'
            }`}
          >
            Export Documents
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('share')}
            className={`pb-1 px-1.5 border-b-2 font-semibold transition-colors cursor-pointer ${
              activeTab === 'share'
                ? 'border-[var(--accent-mint)] text-[var(--accent-mint)]'
                : 'border-transparent text-[var(--text-muted)] hover:text-[var(--text)]'
            }`}
          >
            Shareable Plan Link
          </button>
        </div>

        {/* Tab 1: Export options */}
        {activeTab === 'export' && (
          <div className="space-y-3">
            {/* Markdown */}
            <button
              type="button"
              onClick={handleExportMarkdown}
              className="w-full p-4 rounded-2xl bg-[var(--bg-elev-2)] border border-[var(--border)] hover:border-[var(--accent-sky)] transition-all flex items-center justify-between text-left cursor-pointer group"
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-[var(--accent-sky)]/10 text-[var(--accent-sky)] flex items-center justify-center shrink-0">
                  <FileText className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="text-sm font-bold font-sans text-[var(--text)] group-hover:text-[var(--accent-sky)] transition-colors">
                    Markdown Curriculum (.md)
                  </h4>
                  <p className="text-xs text-[var(--text-muted)]">
                    Clean GitHub-flavored markdown with syllabus, tables, and milestone checkboxes
                  </p>
                </div>
              </div>
              <Download className="w-4 h-4 text-[var(--text-muted)] group-hover:text-[var(--accent-sky)] shrink-0 transition-colors" />
            </button>

            {/* Print / PDF */}
            <button
              type="button"
              onClick={handlePrintPDF}
              className="w-full p-4 rounded-2xl bg-[var(--bg-elev-2)] border border-[var(--border)] hover:border-[var(--accent-mint)] transition-all flex items-center justify-between text-left cursor-pointer group"
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-[var(--accent-mint)]/10 text-[var(--accent-mint)] flex items-center justify-center shrink-0">
                  <Printer className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="text-sm font-bold font-sans text-[var(--text)] group-hover:text-[var(--accent-mint)] transition-colors">
                    Save as PDF / Print
                  </h4>
                  <p className="text-xs text-[var(--text-muted)]">
                    Trigger browser print dialog styled specifically for clean documentation output
                  </p>
                </div>
              </div>
              <Download className="w-4 h-4 text-[var(--text-muted)] group-hover:text-[var(--accent-mint)] shrink-0 transition-colors" />
            </button>

            {/* Raw JSON */}
            <button
              type="button"
              onClick={handleExportJSON}
              className="w-full p-4 rounded-2xl bg-[var(--bg-elev-2)] border border-[var(--border)] hover:border-[var(--accent-purple)] transition-all flex items-center justify-between text-left cursor-pointer group"
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-[var(--accent-purple)]/10 text-[var(--accent-purple)] flex items-center justify-center shrink-0">
                  <Code2 className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="text-sm font-bold font-sans text-[var(--text)] group-hover:text-[var(--accent-purple)] transition-colors">
                    Raw Data Payload (.json)
                  </h4>
                  <p className="text-xs text-[var(--text-muted)]">
                    Machine-readable JSON schema of profile, skill gaps, and roadmap phases
                  </p>
                </div>
              </div>
              <Download className="w-4 h-4 text-[var(--text-muted)] group-hover:text-[var(--accent-purple)] shrink-0 transition-colors" />
            </button>
          </div>
        )}

        {/* Tab 2: Shareable Link */}
        {activeTab === 'share' && (
          <div className="space-y-4">
            <div className="p-4 rounded-2xl bg-[var(--bg-elev-2)] border border-[var(--border)] space-y-2">
              <span className="text-xs font-mono text-[var(--text-muted)] flex items-center gap-1.5">
                <Share2 className="w-3.5 h-3.5 text-[var(--accent-mint)]" />
                Target Role & Configuration Snapshot:
              </span>
              <p className="text-sm font-bold font-sans text-[var(--text)]">
                {profile?.target_role || 'Backend Engineer'} • {roadmap?.available_hours_per_week || 20} hrs/week
              </p>
              <p className="text-xs text-[var(--text-muted)]">
                Anyone with this link can inspect your curriculum benchmark and study timeline.
              </p>
            </div>

            <div className="flex items-center gap-2">
              <input
                type="text"
                readOnly
                value={shareUrl}
                className="flex-1 h-11 px-3 rounded-xl bg-[var(--bg-elev-2)] border border-[var(--border)] font-mono text-xs text-[var(--text-muted)] truncate select-all"
              />
              <button
                type="button"
                onClick={handleCopyShareLink}
                className="h-11 px-4 rounded-xl bg-[var(--accent-mint)] hover:opacity-90 text-black font-bold font-mono text-xs flex items-center gap-1.5 transition-all cursor-pointer shrink-0"
              >
                {copiedLink ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                <span>{copiedLink ? 'Copied!' : 'Copy Link'}</span>
              </button>
            </div>
          </div>
        )}

        {/* Footer */}
        <div className="pt-2 border-t border-[var(--border)] flex justify-between items-center text-xs font-mono text-[var(--text-muted)]">
          <span className="flex items-center gap-1">
            <Sparkles className="w-3.5 h-3.5 text-[var(--accent-mint)]" />
            <span>Deterministic Export Engine</span>
          </span>
          <span>Revision v{roadmap?.version.toFixed(1) || '1.0'}</span>
        </div>
      </div>
    </div>
  );
};
